### PR TITLE
Using Docker caching and the Maven Dependency Plugin

### PR DESCRIPTION
**Pull request by mdcsaenz**
"Fortunately this can be mitigated by Docker caching and the Maven Dependency Plugin. To take advantage of this start by COPY’ing the pom.xml file and RUN’ing the dependency:go-offline goal. This will download most* of the dependencies required for the build and cache them for as long as the pom.xml doesn’t change." [https://nieldw.medium.com/caching-maven-dependencies-in-a-docker-build-dca6ca7ad612](https://nieldw.medium.com/caching-maven-dependencies-in-a-docker-build-dca6ca7ad612)

You can see cached below when rebuilding
```

~/Documents/seneca/WebPokedexGame $ docker build -t seneca:test-1 .
[+] Building 0.6s (15/15) FINISHED                                                                                                                                                                                                      
 => [internal] load build definition from Dockerfile                                                                                                                                                                               0.0s
 => => transferring dockerfile: 491B                                                                                                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                  0.0s
 => => transferring context: 35B                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/openjdk:11-slim                                                                                                                                                                 0.4s
 => [internal] load metadata for docker.io/library/maven:3.8.1-openjdk-11-slim                                                                                                                                                     0.4s
 => [stage-1 1/2] FROM docker.io/library/openjdk:11-slim@sha256:5d1529573ab358fd46b823459bae966ca763ed3c83d568ffc9a0ce6ce1136143                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                  0.0s
 => => transferring context: 10.38kB                                                                                                                                                                                               0.0s
 => [build 1/7] FROM docker.io/library/maven:3.8.1-openjdk-11-slim@sha256:701b37b1bb01daac38c046f6d20c43d594b1ae03bc37089d860ba445866e25c3                                                                                         0.0s
 => CACHED [build 2/7] RUN mkdir -p /workspace                                                                                                                                                                                     0.0s
 => CACHED [build 3/7] WORKDIR /workspace                                                                                                                                                                                          0.0s
 => CACHED [build 4/7] COPY pom.xml /workspace                                                                                                                                                                                     0.0s
 => CACHED [build 5/7] COPY src /workspace/src                                                                                                                                                                                     0.0s
 => CACHED [build 6/7] RUN mvn dependency:go-offline                                                                                                                                                                               0.0s
 => CACHED [build 7/7] RUN mvn -B clean package --file pom.xml -P warren                                                                                                                                                           0.0s
 => CACHED [stage-1 2/2] COPY --from=build /workspace/target/*jar app.jar                                                                                                                                                          0.0s
 => exporting to image                                                                                                                                                                                                             0.0s
 => => exporting layers                                                                                                                                                                                                            0.0s
 => => writing image sha256:71f9b60b85fe43e5bd55bd1b7a7e24509675feb10798bfadfbda815417d6ecd6                                                                                                                                       0.0s
 => => naming to docker.io/library/seneca:test-1 
```

### CODE REVIEW

**Comment by wtvamp** [comment]
It is faster locally - still seems to download everything on each build in the github action.

**Comment by wtvamp** [comment]
I was experimenting with the cache step here: https://medium.com/@alexander.volminger/ci-cd-for-java-maven-using-github-actions-d009a7cb4b8f

But didn't have much luck...still it seems close to what I'm trying to do.

**Comment by mdcsaenz** [comment]
> I was experimenting with the cache step here: https://medium.com/@alexander.volminger/ci-cd-for-java-maven-using-github-actions-d009a7cb4b8f
> 
> But didn't have much luck...still it seems close to what I'm trying to do.

I have an idea, let me revert this change I made and make another change in GHA to build  in GHA the JAR and the BULD the docker image using the GHA cached.

**Comment by mdcsaenz** [comment]
Okay got it to work with this run: https://github.com/Seneca-Foundation/WebPokedexGame/runs/4670619654?check_suite_focus=true


Screen Shot 2021-12-30 at 5 59 11 PM

**Comment by wtvamp** [comment]
Thank you so much for fixing this!  Cristian has a great mentor!

**Pull request merged**
